apiVersion: v1
kind: Service
metadata:
  name: product-api-lb
  labels:
    app: product-api
spec:
  type: LoadBalancer
  selector:
    app: product-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
