apiVersion: v1
kind: Service
metadata:
  name: product-api-lb
  labels:
    app: product-api
spec:
  type: LoadBalancer
  selector:
    app: product-api
  ports:
    - protocol: TCP
      port: 80 # external port (public)
      targetPort: 8000 # container port where app listens
