name: CI / Build, Push image & Deploy to GKE

on:
  push:
    branches:
      - main

env:
  GCP_PROJECT: cme-pre-intern
  GKE_CLUSTER: cme-preintern-gke
  GKE_ZONE: us-central1-a
  IMAGE: gcr.io/cme-pre-intern/product-api
  K8S_MANIFEST_DIR: k8s

permissions:
  contents: read
  id-token: write

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    steps:
      # Fetch repo into runner
      - name: Checkout repository
        uses: actions/checkout@v4

        # Authenticate the runner
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

          # Install gcloud on runner
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.GCP_PROJECT }}
          export_default_credentials: true

        # For docker push
      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker --quiet

      - name: Build Docker image
        run: |
          docker build -t $IMAGE:latest .

      - name: Push image to Artifact Registry
        run: |
          docker push $IMAGE:latest

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          project_id: ${{ env.GCP_PROJECT }}

      - name: Update k8s deployment image
        run: |
          kubectl set image deployment/product-api-deployment product-api=$IMAGE:latest --namespace=default

      - name: Apply manifests
        run: |
          kubectl apply -f ${{ env.K8S_MANIFEST_DIR }}

      - name: Wait for rollout
        run: |
          kubectl rollout status deployment/product-api-deployment --timeout=120s

  post-deploy-tests:
    name: Post-deploy integration tests
    runs-on: ubuntu-latest
    needs: build-push-deploy
    env:
      API_KEY: ${{ secrets.GKE_API_KEY }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          project_id: ${{ env.GCP_PROJECT }}

      - name: Install test dependencies
        run: npm install

      - name: Run Jest integration tests
        run: npm test
